local home = os.getenv("HOME")

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprctl setcursor BreezeX-Light 36")
    hl.exec_cmd("discord")
    hl.exec_cmd("zen-browser")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("python " .. home .. "/.local/bin/razer_keyboard.py")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd(home .. "/.config/hypr/change_wallpapers.sh")
    hl.exec_cmd("/opt/teams-for-linux/teams-for-linux")
end)
