##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Default workspace define for a specific monitor
workspace=1,monitor:eDP-1,default:true
workspace=2,monitor:DP-2,default:true
workspace=3,monitor:DP-1,default:true

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

######################
# Set float by default for specific applications
######################
windowrule = float on, match:class ^(.*dialog.*)$
windowrule = float on, center on, match:class org.gnome.Calculator, match:title Calculator
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class lxappearance
windowrule = float on, size 1600 500, center on, match:class org.pulseaudio.pavucontrol
windowrule = float on, center on, match:class com.gabm.satty

######################
# Inhibit idle
######################
windowrule = idle_inhibit always, workspace 4, match:class teams-for-linux

######################
# Send app to workspace
######################

windowrule = workspace 2, match:class Brave-browser
windowrule = workspace 2, match:class zen
windowrule = workspace 2, match:class Google-chrome
windowrule = workspace 3, match:class discord*
windowrule = workspace 4, match:class Bitwarden

######################
# intellij (native wayland 2026.1+)
######################
windowrule = no_initial_focus on, match:class ^jetbrains-(?!toolbox), match:float 1

windowrule = float on, center on, match:title ^(.*popup.*|.*dialog.*|find.*|search.*)$

######################
# blur effect rules
###################
# windowrulev2 = opacity 0.9, class:com.mitchellh.ghostty

